#!/bin/bash
echo " -------------->>>> esxd001-pc1 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd001-pc1 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd001-pc3 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd001-pc3 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd001-pc5 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd001-pc5 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd001-pc7 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd001-pc7 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd001-pc9 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd001-pc9 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 

echo " -------------->>>> esxd003-pc1 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd003-pc1 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd003-pc3 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd003-pc3 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd003-pc5 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd003-pc5 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc "
 echo " -------------->>>> esxd003-pc7 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd003-pc7 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd003-pc9 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd003-pc9 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 
echo " -------------->>>> esxd003-pc11 >>>>-----------"
perl $SQAROOT/bin/1.0/common/sshcli.pl  -n -d  esxd003-pc11 -u root -p actiontec -v "ps -aux | grep gflaunch " -v "ps -aux | grep gflaunch | wc " 

