#!/bin/bash
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc1 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc2 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc3 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc4 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc5 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc6 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc7 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc8 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc9 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd001-pc10 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 


perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc1 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc2 -u root -p actiontec -v "ntpdate -u 0.pool
.ntp.org" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc3 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc4 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc5 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc6 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc7 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc8 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc9 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc10 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd003-pc11 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 

perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc1 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc2 -u root -p actiontec -v "ntpdate -u 0.pool
.ntp.org" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc3 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc4 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc5 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc6 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc7 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc8 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc9 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc10 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock" 
perl $SQAROOT/bin/1.0/common/sshcli.pl  -d esxd002-pc11 -u root -p actiontec -v "ntpdate -u  0.pool.ntp.org" -v "hwclock --systohc" -v "hwclock"